### PR TITLE
fix: support blobfuse2 install for GKE cos node

### LINKED ISSUE #2109: install-blobfuse-proxy init-container fails on GKE/COS nodes due to read-only filesystem
The Azure Blob CSI driver (v1.26.3) controller pods deploy successfully, but node pods fail because the install-blobfuse-proxy init-container cannot write to /host/usr/bin on Container-Optimized OS (COS) nodes. 

This is identical to [Issue #1645](https://github.com/kubernetes-sigs/blob-csi-driver/issues/1645) (fixed for Linux Gartner), but COS requires a separate fix due to its immutable filesystem.

Initially it gives error for `/opt` which i fixed by changing it to `/var` but now its giving below error

**Error:**

```
+ INSTALL_BLOBFUSE_PROXY=true
+ DISABLE_UPDATEDB=true
+ SET_MAX_OPEN_FILE_NUM=true
+ SET_READ_AHEAD_SIZE=true
+ MIGRATE_K8S_REPO=false
+ READ_AHEAD_KB=15380
+ KUBELET_PATH=/var/lib/kubelet
+ [ /var/lib/kubelet != /var/lib/kubelet ]
+ HOST_CMD=nsenter --mount=/proc/1/ns/mnt
+ nsenter --mount=/proc/1/ns/mnt cat /etc/os-release
+ grep ^ID=
+ cut -d= -f2
+ tr -d "
+ DISTRIBUTION=cos
+ nsenter --mount=/proc/1/ns/mnt uname -m
+ ARCH=x86_64
+ echo Linux distribution: cos, Arch: x86_64
+ . ./blobfuse-proxy/install-proxy.sh
+ set -xe
Linux distribution: cos, Arch: x86_64
+ [ cos != ubuntu ]
+ echo skip install blobfuse/blobfuse2 for cos....
skip install blobfuse/blobfuse2 for cos....
+ [ true = true ]
+ updateBlobfuseProxy=true
+ [ -f /host/usr/bin/blobfuse-proxy ]
+ [ true = true ]
+ echo copy blobfuse-proxy....
+ rm -rf /host//var/lib/kubelet/plugins/blob.csi.azure.com/blobfuse-proxy.sock
copy blobfuse-proxy....
+ cp /blobfuse-proxy/blobfuse-proxy /host/usr/bin/blobfuse-proxy --force
cp: cannot create regular file '/host/usr/bin/blobfuse-proxy': Read-only file system
```

**Affected Components:**
Working: csi-blob-controller pods (deploy successfully).

Failing: csi-blob-node pods (stuck in Init:Error due to init-container).

**Expected Behavior:**
The init-container should:
Use COS-approved writable paths (e.g., /home/kubernetes/bin).

**Proposed Fix:**
Extend the Linux Gartner fix to:

Add COS detection in the init-container script.

Redirect installation to /home/kubernetes/bin (COS allows writes here).

@andyzhangx whats plan for new release with OS like gardenlinux and cos? It will help to use driver with these kind of OS.

### PR DESCRIPTION
**Pull request by andyzhangx**
**What type of PR is this?**
/kind bug

**What this PR does / why we need it**:
fix: support blobfuse2 install for GKE cos node

on GKE cos node, we should set following mount option for blobfuse volume due to error `failed to create default work dir [mkdir /.blobfuse2: read-only file system]`:
```
    - --default-working-dir=/home/mnt
    - --tmp-path=/home/mnt
```

**Which issue(s) this PR fixes**:

Fixes #2109, #1645, #2113

**Requirements**:
- [ ] uses [conventional commit messages](https://www.conventionalcommits.org/)
  
- [ ] includes documentation
- [ ] adds unit tests
- [ ] tested upgrade from previous version

**Special notes for your reviewer**:

**Release note**:
```
none
```

### CODE REVIEW

**Comment by imranrazakhan** [comment]
@andyzhangx Can we merge it to master?

File: pkg/blobfuse-proxy/install-proxy-rhcos.sh [hunk 1]
```diff
@@ -34,15 +48,15 @@ else
...
+  chmod 755 /host/${BIN_PATH}/blobfuse2
 fi
 
 if [ "${INSTALL_BLOBFUSE_PROXY}" = "true" ];then
   # install blobfuse-proxy
   updateBlobfuseProxy="true"
-  if [ -f "/host/usr/local/bin/blobfuse-proxy" ];then
-    old=$(sha256sum /host/usr/local/bin/blobfuse-proxy | awk '{print $1}')
+  if [ -f "/host/${BIN_PATH}/blobfuse-proxy" ];then
+    old=$(sha256sum /host/${BIN_PATH}/blobfuse-proxy | awk '{print $1}')
```
Comment (the-veloper) [inline pkg/blobfuse-proxy/install-proxy-rhcos.sh:59]: bin path already contains `/`
this causes double `/` like: `/host//home/kubernetes/bin/...`

Comment (andyzhangx) [reply pkg/blobfuse-proxy/install-proxy-rhcos.sh:59]: that's ok, it should work on Linux, right?

Comment (the-veloper) [reply pkg/blobfuse-proxy/install-proxy-rhcos.sh:59]: yeah, i tested it and that works, although it is ugly.
problem is that /host is not mounted on the init container, so none of the custom paths can work:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/charts/latest/blob-csi-driver/templates/csi-blob-node.yaml#L110

Comment (the-veloper) [reply pkg/blobfuse-proxy/install-proxy-rhcos.sh:59]: we can mount /home/kubernetes/bin and /var/bin for cos and gardenlinux and introduce additional mounts for when a custom bin path is required, so that we don't expose the entire /host? wdyt @andyzhangx
